config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do 
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
 
  resources :users

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"} do
    resources :orders
    resources :tickets  
    resources :carts
    resources :documents
    resources :flights
    
    root 'store#index', as: 'store_index', via: :all
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :tickets, dependent: :destroy

    def add_flight(flight)
        current_ticket = tickets.find_by(flight_id: flight.id)
        if current_ticket 
            current_ticket.quantity += 1
        else 
            current_ticket = tickets.build(flight_id: flight.id)
        end
        current_ticket
    end
end

app/models/document.rb
class Document < ApplicationRecord
    validates :document_type, presence: true
    validates :expiration_date, presence: true

    belongs_to :users, optional: true
end

app/models/flight.rb
class Flight < ApplicationRecord
    validates :total_seats, presence: true, numericality: true
    validates :destination, presence: true
    validates :departure_time, presence: true
    validates :arrival_time, presence: true

    has_many :tickets
    before_destroy :ensure_not_referenced_by_ticket

    private

    # method below
    def ensure_not_referenced_by_ticket 
        unless tickets.empty?
            errors.add(:base, 'Tickets are present')
            throw :abort
        end
    end
end

app/models/order.rb
require 'pago'

class Order < ApplicationRecord
    enum pay_type: {
        "Credit Card" => 0,
        "Debit Card" => 1,
        "PayPal" => 2
}
    has_many :tickets, dependent: :destroy

    validates :full_name, :mailing_address, :country, :city, :email, presence: true
    validates :pay_type, inclusion: pay_types.keys

    def add_tickets_from_cart(cart)
        cart.tickets.each do |ticket|
            ticket.cart_id = nil
            tickets << ticket
        end
    end

    def charge!(pay_type_params)
        payment_details = {}
        payment_method = nil 
        case pay_type 
        when "Credit Card"
            payment_method = :credit_card
            month, year = pay_type_params[:expiration_date].split(//)
            payment_details[:cc_number] = pay_type_params[:credit_card_number]
            payment_details[:expiration_month] = month
            payment_details[:expiration_year] = year 
        when "Debit Card"
            payment_method = :debit_card
            month, year = pay_type_params[:expiration_date].split(//)
            payment_details[:debit_number] = pay_type_params[:debit_card_number]
            payment_details[:expiration_month] = month
            payment_details[:expiration_year] = year 
        when "PayPal" 
            payment_method = :paypal 
            payment_details[:username] = pay_type_params[:username]
            payment_details[:password] = pay_type_params[:password]
        end 

        payment_result = Pago.make_payment(
            order_id: id,
            payment_method: payment_method,
            payment_details: payment_details
        )

        if payment_result.succeeded?
            OrderMailer.received(self).deliver_later
            OrderMailer.itinerary(self).deliver_later
        else
            raise payment_result.error
        end
    end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :flight
  # ^ not optional to belong to flight,
  # since a flight has many tickets and
  # that is a fact for these models
  belongs_to :cart, optional: true
  # ^ add optional: true to Cart association
  # because before & after being purchased, the 
  # ticket would not belong to the cart
  # and while being purchased it does!
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize, only: [:create, :update, :destroy]
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil 
    respond_to do |format|
      format.html { redirect_to store_index_url, notice: 'Cart has been destroyed' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    # Send flash notice if invalid cart is trying to be accessed
    def invalid_cart 
      logger.error "Trying to access an invalid cart #{params[:id]}"
      redirect_to store_index_url, notice: 'Invalid Cart'
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_action :authorize
  include CurrentCart
  before_action :set_cart

  def index
    if params[:set_locale]
      redirect_to store_index_url(locale: params[:set_locale])
    else
      @flights = Flight.order(:destination)
    end
  end

  def displayFlightsByDate 
    @flights = Flight.order(:departure_time)
    # fix this later to order based on cheapest prices ASC
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def render_if_not_empty(condition, cart_contents)
        if condition
            render cart_contents
        end
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<p>
    Currently, it is <%= Time.now %>.
    <%= pluralize(@total_orders, "order") %> for flight tickets have been made!
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<link rel="stylesheet" href="https://sdks.shopifycdn.com/polaris/latest/polaris.css" />

  <head>
    <title>Interstellar Flights</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script type="text/javascript">
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale = "<%= I18n.locale %>";
    </script>
  </head>

  <body>
    <!-- animated star background elements -->
  <div class="stars"></div>
  <div class="twinkling"></div>
  <div class="clouds">
  
  
<div class="flex-item">
<div id="sidebar-right" class="Polaris-Card">
  <ul class="Polaris-OptionList">
    <li class="Polaris-OptionList__Options">
      <p class="Polaris-OptionList__Title"></p>

          <!-- Locale switcher -->
          <aside>
            <%= form_tag store_index_path, class: 'locale' do %>
              <%= select_tag 'set_locale',
              options_for_select(LANGUAGES, I18n.locale.to_s),
              onchange: 'this.form.submit()' %> 
            <%= submit_tag 'submit', id: "submit_locale_change" %>
            <% end %>
          </aside>

        <% if @cart %>
        <div id="cart" class="carts">
          <%= render_if_not_empty @cart && @cart.tickets.any?, @cart %>
        </div>
        <% end %>
        
      <ul class="Polaris-OptionList__Options">
        <li class="Polaris-OptionList-Option" tabindex="-1"><button type="button" class="Polaris-OptionList-Option__SingleSelectOption"><%= link_to t('.catalog'), '/' %></button></li>
        <li class="Polaris-OptionList-Option" tabindex="-1"><button type="button" class="Polaris-OptionList-Option__SingleSelectOption"><%= link_to t('.contact'), '/' %></button></li>
      </ul>

      <% if session[:user_id] %>
      <!-- If logged in, show admin sidebar options as well -->
      <ul class="Polaris-OptionList__Options">
        <li class="Polaris-OptionList-Option" tabindex="-1"><button type="button" class="Polaris-OptionList-Option__SingleSelectOption"><%= link_to t('.order'), orders_path %></button></li>
        <li class="Polaris-OptionList-Option" tabindex="-1"><button type="button" class="Polaris-OptionList-Option__SingleSelectOption"><%= link_to t('.user'), users_path %></button></li>
        <li class="Polaris-OptionList-Option" tabindex="-1"><button type="button" class="Polaris-OptionList-Option__SingleSelectOption"><%= link_to t('.flight'), flights_path %></button></li>
        <li class="Polaris-OptionList-Option" tabindex="-1"><button type="button" class="Polaris-OptionList-Option__SingleSelectOption"><%= link_to t('.logout'), logout_path, method: :delete %></button></li>
      </ul>
      <% end %>
    </li>
  </ul>
</div>
    <%= yield %>
</div>

</div>
  </body>
</html>